### ISSUE TITLE
Syntax Error in 1.37

### ISSUE THREAD

**Issue by RhinosF1** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#14]
**Describe the bug**
Warning: Syntax error [Called from MediaWiki\Extension\EmbedVideo\Media\FFProbe\FFProbe::invokeFFProbe in /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/FFProbe/FFProbe.php at line 165] in /srv/mediawiki/w/includes/debug/MWDebug.php on line 498

**Technical information:**
 - OS: Debian 11
 - Extension Version 76cefce
 - MediaWiki Version 1.37.0-beta

**Comment by octfx** [comment]
The extension was passing a wrong filepath to ffprobe. Could you test again using the current develop branch?

Also, when and where does the error occur? On a file page or when including a local file using `[[File...` ?

**Comment by octfx** [comment]
> > The extension was passing a wrong filepath to ffprobe. Could you test again using the current develop branch?
> 
> Which specific commit?

83af7367924e7b043815cbc76c3885e6039810d8

**Comment by octfx** [comment]
Perfect
I'll merge this into master with the following release

**Comment by Universal-Omega** [comment]
@octfx

On 1.36 (without the mentioned commit) this is given:
```
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `'/usr/bin/ffprobe' -v quiet -print_format json -show_format -show_streams mwstore://local-backend/local-public/8/80/Example.mp3'
```
full message:
```
Error running '/usr/bin/firejail' '--quiet' '--profile=/srv/mediawiki/w/includes/shell/firejail.profile' -- /bin/bash '/srv/mediawiki/w/vendor/wikimedia/shellbox/src/Command/limit.sh' ''\''/usr/bin/ffprobe'\'' -v quiet -print_format json -show_format -show_streams mwstore://local-backend/local-public/8/80/Example.mp3' 'SB_INCLUDE_STDERR=;SB_CPU_LIMIT=180; SB_CGROUP='\'''\''; SB_MEM_LIMIT=2147483648; SB_FILE_SIZE_LIMIT=104857600; SB_WALL_CLOCK_LIMIT=180; SB_USE_LOG_PIPE=yes': /bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `'/usr/bin/ffprobe' -v quiet -print_format json -show_format -show_streams mwstore://local-backend/local-public/8/80/Example.mp3'
```
in addition to this (full backtrace given):
```
PHP Warning: Syntax error [Called from MediaWiki\Extension\EmbedVideo\Media\FFProbe\FFProbe::invokeFFProbe in /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/FFProbe/FFProbe.php at line 165]

from /srv/mediawiki/w/includes/debug/MWDebug.php(499)
#0 [internal function]: MWExceptionHandler::handleError(integer, string, string, integer, array)
#1 /srv/mediawiki/w/includes/debug/MWDebug.php(499): trigger_error(string, integer)
#2 /srv/mediawiki/w/includes/debug/MWDebug.php(194): MWDebug::sendMessage(string, string, integer)
#3 /srv/mediawiki/w/includes/GlobalFunctions.php(1095): MWDebug::warning(string, integer, integer, string)
#4 /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/FFProbe/FFProbe.php(165): wfLogWarning(string)
#5 /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/FFProbe/FFProbe.php(51): MediaWiki\Extension\EmbedVideo\Media\FFProbe\FFProbe->invokeFFProbe()
#6 /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/FFProbe/FFProbe.php(72): MediaWiki\Extension\EmbedVideo\Media\FFProbe\FFProbe->getMetaData()
#7 /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/AudioHandler.php(328): MediaWiki\Extension\EmbedVideo\Media\FFProbe\FFProbe->getStream(string)
#8 /srv/mediawiki/w/includes/poolcounter/PoolCounterWorkViaCallback.php(74): MediaWiki\Extension\EmbedVideo\Media\AudioHandler::MediaWiki\Extension\EmbedVideo\Media\{closure}()
#9 /srv/mediawiki/w/includes/poolcounter/PoolCounterWork.php(162): PoolCounterWorkViaCallback->doWork()
#10 /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/AudioHandler.php(342): PoolCounterWork->execute()
#11 /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/AudioHandler.php(254): MediaWiki\Extension\EmbedVideo\Media\AudioHandler->getMakeProbeFromPool(LocalFile, string)
#12 /srv/mediawiki/w/includes/filerepo/file/File.php(2315): MediaWiki\Extension\EmbedVideo\Media\AudioHandler->getLongDesc(LocalFile)
#13 /srv/mediawiki/w/includes/page/ImagePage.php(517): File->getLongDesc()
#14 /srv/mediawiki/w/includes/page/ImagePage.php(141): ImagePage->openShowImage()
#15 /srv/mediawiki/w/includes/actions/ViewAction.php(74): ImagePage->view()
#16 /srv/mediawiki/w/includes/MediaWiki.php(531): ViewAction->show()
#17 /srv/mediawiki/w/includes/MediaWiki.php(315): MediaWiki->performAction(ImagePage, Title)
#18 /srv/mediawiki/w/includes/MediaWiki.php(913): MediaWiki->performRequest()
#19 /srv/mediawiki/w/includes/MediaWiki.php(546): MediaWiki->main()
#20 /srv/mediawiki/w/index.php(53): MediaWiki->run()
#21 /srv/mediawiki/w/index.php(46): wfIndexMain()
#22 {main}
``` 

when using for example, `[[File:Example.mp3]]`. though at least the embed content still seems to render.

However on 1.37, and with the commit applied, a fatal exception is given when trying to upload an mp3 file:
```
Call to undefined method FSFile::getLocalRefPath()

from /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/FFProbe/FFProbe.php(126)
#0 /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/FFProbe/FFProbe.php(157): MediaWiki\Extension\EmbedVideo\Media\FFProbe\FFProbe->getFilePath()
#1 /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/FFProbe/FFProbe.php(51): MediaWiki\Extension\EmbedVideo\Media\FFProbe\FFProbe->invokeFFProbe()
#2 /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/FFProbe/FFProbe.php(72): MediaWiki\Extension\EmbedVideo\Media\FFProbe\FFProbe->getMetaData()
#3 /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/AudioHandler.php(328): MediaWiki\Extension\EmbedVideo\Media\FFProbe\FFProbe->getStream(string)
#4 /srv/mediawiki/w/includes/poolcounter/PoolCounterWorkViaCallback.php(74): MediaWiki\Extension\EmbedVideo\Media\AudioHandler::MediaWiki\Extension\EmbedVideo\Media\{closure}()
#5 /srv/mediawiki/w/includes/poolcounter/PoolCounterWork.php(162): PoolCounterWorkViaCallback->doWork()
#6 /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/AudioHandler.php(342): PoolCounterWork->execute()
#7 /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/AudioHandler.php(278): MediaWiki\Extension\EmbedVideo\Media\AudioHandler->getMakeProbeFromPool(FSFile)
#8 /srv/mediawiki/w/includes/media/MediaHandler.php(236): MediaWiki\Extension\EmbedVideo\Media\AudioHandler->getMetadata(FSFile, string)
#9 /srv/mediawiki/w/includes/utils/MWFileProps.php(88): MediaHandler->getSizeAndMetadataWithFallback(FSFile, string)
#10 /srv/mediawiki/w/includes/upload/UploadBase.php(552): MWFileProps->getPropsFromPath(string, string)
#11 /srv/mediawiki/w/includes/upload/UploadBase.php(485): UploadBase->verifyPartialFile()
#12 /srv/mediawiki/w/includes/upload/UploadBase.php(391): UploadBase->verifyFile()
#13 /srv/mediawiki/w/includes/upload/UploadFromFile.php(95): UploadBase->verifyUpload()
#14 /srv/mediawiki/w/includes/specials/SpecialUpload.php(550): UploadFromFile->verifyUpload()
#15 /srv/mediawiki/w/includes/specials/SpecialUpload.php(244): SpecialUpload->processUpload()
#16 /srv/mediawiki/w/includes/specialpage/SpecialPage.php(647): SpecialUpload->execute(NULL)
#17 /srv/mediawiki/w/includes/specialpage/SpecialPageFactory.php(1366): SpecialPage->run(NULL)
#18 /srv/mediawiki/w/includes/MediaWiki.php(314): MediaWiki\SpecialPage\SpecialPageFactory->executePath(string, RequestContext)
#19 /srv/mediawiki/w/includes/MediaWiki.php(925): MediaWiki->performRequest()
#20 /srv/mediawiki/w/includes/MediaWiki.php(559): MediaWiki->main()
#21 /srv/mediawiki/w/index.php(53): MediaWiki->run()
#22 /srv/mediawiki/w/index.php(46): wfIndexMain()
#23 {main}
```

**Comment by octfx** [comment]
@Universal-Omega thanks for this!

The mentioned commit indeed had another error... 🙄
Commit 4e0148278832534d9e8c345fff864c544a160a60 handles the case when a `FSFile` is present. This should fix the upload problem

As for the `FFProbe::invokeFFProbe` I think that too should be fixed by this

**Comment by alistair3149** [comment]
Seems to be fixed. Closing this now.
