### ISSUE TITLE
Error after installing in the Docker container

### ISSUE THREAD

**Issue by Alexander231299** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#78]
**Describe the bug**
MediaWiki internal error after installing extension in the Docker container.

**To Reproduce**
1. Build own container with dockerfile
```
FROM mediawiki:1.41.0

RUN mkdir -p /var/www/html/extensions/EmbedVideo/
COPY mediawiki-extensions-EmbedVideo-3.4.1/*.* /var/www/html/extensions/EmbedVideo/
RUN    chown -R www-data:www-data /var/www/html/extensions/EmbedVideo/
```
3. Modify localsettings.php
4. start container & go to the main page
5. See error

**Expected behavior**
Start page open

**Technical information:**
 - OS: Docker
 - Browser chrome
 - Extension Version 3.4.1
 - MediaWiki Version 1.41.0]

**Additional context**
```
MediaWiki internal error.

Original exception: [36da5a53758030a579a6d14a] /index.php TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, class "MediaWiki\Extension\EmbedVideo\EmbedVideoHooks" not found
Backtrace:
from /var/www/html/includes/Setup.php(570)
#0 /var/www/html/includes/WebStart.php(92): require_once()
#1 /var/www/html/index.php(44): require(string)
#2 {main}

Exception caught inside exception handler: [36da5a53758030a579a6d14a] /index.php Error: Class "MediaWiki\Extension\EmbedVideo\EmbedVideoHooks" not found
Backtrace:
from /var/www/html/vendor/wikimedia/object-factory/src/ObjectFactory.php(240)
#0 /var/www/html/vendor/wikimedia/object-factory/src/ObjectFactory.php(149): Wikimedia\ObjectFactory\ObjectFactory::getObjectFromSpec(array, array)
#1 /var/www/html/includes/HookContainer/HookContainer.php(258): Wikimedia\ObjectFactory\ObjectFactory->createObject(array)
#2 /var/www/html/includes/HookContainer/HookContainer.php(350): MediaWiki\HookContainer\HookContainer->makeExtensionHandlerCallback(string, array, array)
#3 /var/www/html/includes/HookContainer/HookContainer.php(525): MediaWiki\HookContainer\HookContainer->normalizeHandler(string, array, array)
#4 /var/www/html/includes/HookContainer/HookContainer.php(148): MediaWiki\HookContainer\HookContainer->getHandlers(string, array)
#5 /var/www/html/includes/HookContainer/HookRunner.php(2954): MediaWiki\HookContainer\HookContainer->run(string, array)
#6 /var/www/html/includes/parser/Parser.php(486): MediaWiki\HookContainer\HookRunner->onParserFirstCallInit(Parser)
#7 /var/www/html/includes/parser/ParserFactory.php(220): Parser->__construct(MediaWiki\Config\ServiceOptions, MediaWiki\Parser\MagicWordFactory, Language, ParserFactory, MediaWiki\Utils\UrlUtils, MediaWiki\SpecialPage\SpecialPageFactory, MediaWiki\Linker\LinkRendererFactory, MediaWiki\Title\NamespaceInfo, MediaWiki\Logger\LegacyLogger, MediaWiki\Page\File\BadFileLookup, MediaWiki\Languages\LanguageConverterFactory, MediaWiki\HookContainer\HookContainer, MediaWiki\Tidy\RemexDriver, WANObjectCache, MediaWiki\User\UserOptionsManager, MediaWiki\User\UserFactory, MediaWiki\Title\MediaWikiTitleCodec, MediaWiki\Http\HttpRequestFactory, MediaWiki\Category\TrackingCategories, MediaWiki\Preferences\SignatureValidatorFactory, MediaWiki\User\UserNameUtils)
#8 /var/www/html/includes/language/MessageCache.php(1454): ParserFactory->create()
#9 /var/www/html/includes/language/MessageCache.php(1435): MessageCache->getParser()
#10 /var/www/html/includes/language/Message.php(1468): MessageCache->transform(string, boolean, Language, NULL)
#11 /var/www/html/includes/language/Message.php(1011): Message->transformText(string)
#12 /var/www/html/includes/language/Message.php(1059): Message->format(string)
#13 /var/www/html/includes/exception/MWExceptionRenderer.php(254): Message->text()
#14 /var/www/html/includes/exception/MWExceptionRenderer.php(196): MWExceptionRenderer::msg(string, string, string)
#15 /var/www/html/includes/exception/MWExceptionRenderer.php(105): MWExceptionRenderer::reportHTML(TypeError)
#16 /var/www/html/includes/exception/MWExceptionHandler.php(134): MWExceptionRenderer::output(TypeError, integer)
#17 /var/www/html/includes/exception/MWExceptionHandler.php(251): MWExceptionHandler::report(TypeError)
#18 /var/www/html/includes/exception/MWExceptionHandler.php(219): MWExceptionHandler::handleException(TypeError, string)
#19 [internal function]: MWExceptionHandler::handleUncaughtException(TypeError)
#20 {main}

Notice: Uncommitted DB writes (transaction from Wikimedia\Rdbms\Database::beginIfImplied (MediaWiki\Revision\RevisionStore::fetchRevisionRowFromConds)) in /var/www/html/includes/libs/rdbms/database/TransactionManager.php on line 586

Notice: DB transaction writes or callbacks still pending (LCStoreDB::finishWrite, LCStoreDB::finishWrite, LCStoreDB::finishWrite, LCStoreDB::finishWrite, LCStoreDB::finishWrite, LCStoreDB::finishWrite, LCStoreDB::finishWrite, LCStoreDB::finishWrite, LCStoreDB::finishWrite, LCStoreDB::finishWrite, LCStoreDB::finishWrite, LCStoreDB::finishWrite, LCStoreDB::finishWrite, LCStoreDB::finishWrite, LCStoreDB::finishWrite, LCStoreDB::finishWrite, LCStoreDB::finishWrite, LCStoreDB::finishWrite, LCStoreDB::finishWrite, LCStoreDB::finishWrite) in /var/www/html/includes/libs/rdbms/database/Database.php on line 3344
```

**Comment by octfx** [comment]
What’s the content of the EmbedVideo folder in your container?

You could alternatively install the extension via composer.

I'm using the extension in docker myself without seeing this error

**Comment by Alexander231299** [comment]
> Каково содержимое папки EmbedVideo в вашем контейнере?
> 

root@mediawiki-2:/var/www/html/extensions/EmbedVideo# ls -la                     
total 68                                                                         
drwxr-xr-x 1 www-data www-data   326 Jan  6 15:53 .                              
drwxr-xr-x 1 www-data www-data   700 Jan  6 15:52 ..                             
-rw-rw-r-- 1 www-data www-data    63 Dec 14 09:13 .eslintignore                  
-rw-rw-r-- 1 www-data www-data   374 Dec 14 09:13 .eslintrc.json                 
-rw-rw-r-- 1 www-data www-data   105 Dec 14 09:13 .gitignore                     
-rw-rw-r-- 1 www-data www-data   565 Dec 14 09:13 .phpcs.xml                     
-rw-rw-r-- 1 www-data www-data  7529 Dec 14 09:13 CHANGES.md                     
-rw-rw-r-- 1 www-data www-data   196 Dec 14 09:13 CREDITS.md                     
-rw-rw-r-- 1 www-data www-data   774 Dec 14 09:13 EmbedVideo.i18n.magic.php      
drwxrwxr-x 1 www-data www-data   110 Dec 14 09:13 ISSUE_TEMPLATE                 
-rw-rw-r-- 1 www-data www-data 19299 Dec 14 09:13 README.md                      
-rw-rw-r-- 1 www-data www-data   906 Dec 14 09:13 composer.json                  
-rw-rw-r-- 1 www-data www-data  5969 Dec 14 09:13 extension.json                 
-rw-rw-r-- 1 www-data www-data   394 Dec 14 09:13 package.json                   
drwxrwxr-x 1 www-data www-data    68 Dec 14 09:13 workflows

**Comment by octfx** [comment]
You are missing all folders like `includes` or `resources`.

I think you need to change your copy command to

`COPY mediawiki-extensions-EmbedVideo-3.4.1/* /var/www/html/extensions/EmbedVideo/`

Where `*.*` is now `*`

**Comment by Alexander231299** [comment]
Thanks, my mistake.
the right command is 
```
COPY mediawiki-extensions-EmbedVideo-3.4.1 /var/www/html/extensions/EmbedVideo/
```

**Comment by Alexander231299** [comment]
Problem solved
