### ISSUE TITLE
AudioTransformOutput.php: PHP Notice: Undefined index: descriptionUrl

### ISSUE THREAD

**Issue by kghbln** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#88]
## Setup
- [MediaWiki](https://www.mediawiki.org/) 	[1.39.6](https://www.mediawiki.org/wiki/MediaWiki_1.39) [(0e03068)](https://gerrit.wikimedia.org/g/mediawiki/core.git/+/0e030687a02c86db1a992322af4e62a00f2337da) 2024-03-11T16:26:30
- [PHP](https://php.net/) 	8.1.2-1ubuntu2.14 (apache2handler)
- [MariaDB](https://mariadb.org/) 	10.6.16-MariaDB-0ubuntu0.22.04.1
- [EmbedVideo](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo)	3.4.1 (108cbb0) 2023-12-14T10:13:56

## Issue
I am getting these error exceptions in my log:
```
[8f3983208b71092aca272001] [no req]   ErrorException from line 97 of /../w/extensions/EmbedVideo/classes/media/AudioTransformOutput.php: PHP Notice: Undefined index: descriptionUrl
```
## Backtrace
```
#0 /../w/extensions/EmbedVideo/classes/media/AudioTransformOutput.php(97): MWExceptionHandler::handleError()
#1 /../w/includes/Linker.php(615): EmbedVideo\AudioTransformOutput->toHtml()
#2 /../w/includes/Linker.php(395): Linker::makeThumbLink2()
#3 /../w/includes/parser/Parser.php(5391): Linker::makeImageLink()
#4 /../w/includes/parser/Parser.php(2635): Parser->makeImage()
#5 /../w/includes/parser/Parser.php(2382): Parser->handleInternalLinks2()
#6 /../w/includes/parser/Parser.php(1586): Parser->handleInternalLinks()
#7 /../w/includes/parser/Parser.php(652): Parser->internalParse()
#8 /../w/includes/content/WikitextContent.php(374): Parser->parse()
#9 /../w/includes/content/AbstractContent.php(590): WikitextContent->fillParserOutput()
#10 /../w/includes/Revision/RenderedRevision.php(263): AbstractContent->getParserOutput()
#11 /../w/includes/Revision/RenderedRevision.php(235): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached()
#12 /../w/includes/Revision/RevisionRenderer.php(215): MediaWiki\Revision\RenderedRevision->getSlotParserOutput()
#13 /../w/includes/Revision/RevisionRenderer.php(152): MediaWiki\Revision\RevisionRenderer->combineSlotOutput()
#14 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}()
#15 /../w/includes/Revision/RenderedRevision.php(197): call_user_func()
#16 /../w/includes/Storage/DerivedPageDataUpdater.php(1315): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#17 [internal function]: MediaWiki\Storage\DerivedPageDataUpdater->getCanonicalParserOutput()
#18 /../w/includes/edit/PreparedEdit.php(104): call_user_func()
#19 /../w/includes/edit/PreparedEdit.php(119): MediaWiki\Edit\PreparedEdit->getOutput()
#20 /../w/includes/Storage/DerivedPageDataUpdater.php(1293): MediaWiki\Edit\PreparedEdit->__get()
#21 /../w/includes/page/WikiPage.php(2117): MediaWiki\Storage\DerivedPageDataUpdater->getPreparedEdit()
#22 /../w/extensions/SpamBlacklist/includes/SpamBlacklistHooks.php(34): WikiPage->prepareContentForEdit()
#23 /../w/includes/HookContainer/HookContainer.php(329): SpamBlacklistHooks::filterMergedContent()
#24 /../w/includes/HookContainer/HookContainer.php(132): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#25 /../w/includes/HookContainer/HookRunner.php(1529): MediaWiki\HookContainer\HookContainer->run()
#26 /../w/includes/EditPage.php(1906): MediaWiki\HookContainer\HookRunner->onEditFilterMergedContent()
#27 /../w/includes/EditPage.php(2365): EditPage->runPostMergeFilters()
#28 /../w/includes/EditPage.php(1726): EditPage->internalAttemptSave()
#29 /../w/includes/api/ApiEditPage.php(433): EditPage->attemptSave()
#30 /../w/includes/api/ApiMain.php(1593): ApiEditPage->execute()
#31 /../w/includes/api/ApiMain.php(529): ApiMain->executeAction()
#32 /../w/includes/api/ApiMain.php(500): ApiMain->executeActionWithErrorHandling()
#33 /../w/api.php(90): ApiMain->execute()
#34 /../w/api.php(45): wfApiMain()
#35 {main}
```
See also https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/issues/89

**Comment by kghbln** [comment]
per https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/issues/89#issuecomment-2007678778
