### ISSUE TITLE
AudioTransformOutput.php: PHP Notice: Undefined variable: class

### ISSUE THREAD

**Issue by kghbln** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#89]
## Setup
- [MediaWiki](https://www.mediawiki.org/) 	[1.39.6](https://www.mediawiki.org/wiki/MediaWiki_1.39) [(0e03068)](https://gerrit.wikimedia.org/g/mediawiki/core.git/+/0e030687a02c86db1a992322af4e62a00f2337da) 2024-03-11T16:26:30
- [PHP](https://php.net/) 	8.1.2-1ubuntu2.14 (apache2handler)
- [MariaDB](https://mariadb.org/) 	10.6.16-MariaDB-0ubuntu0.22.04.1
- [EmbedVideo](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo)	3.4.1 (108cbb0) 2023-12-14T10:13:56

## Issue
I am getting these error exceptions in my log:
```
[51d9ecc324bb7a4ce4ccb607] [no req]   ErrorException from line 102 of /../w/extensions/EmbedVideo/classes/media/AudioTransformOutput.php: PHP Notice: Undefined variable: class
```
## Backtrace
```
#0 /../w/extensions/EmbedVideo/classes/media/AudioTransformOutput.php(102): MWExceptionHandler::handleError()
#1 /../w/includes/Linker.php(430): EmbedVideo\AudioTransformOutput->toHtml()
#2 /../w/includes/parser/Parser.php(5391): Linker::makeImageLink()
#3 /../w/includes/parser/Parser.php(2635): Parser->makeImage()
#4 /../w/includes/parser/Parser.php(2382): Parser->handleInternalLinks2()
#5 /../w/includes/parser/Parser.php(1586): Parser->handleInternalLinks()
#6 /../w/includes/parser/Parser.php(851): Parser->internalParse()
#7 /../w/extensions/Cite/src/ReferencesFormatter.php(73): Parser->recursiveTagParse()
#8 /../w/extensions/Cite/src/Cite.php(502): Cite\ReferencesFormatter->formatReferences()
#9 /../w/extensions/Cite/src/Cite.php(474): Cite\Cite->formatReferences()
#10 /../w/extensions/Cite/src/Cite.php(421): Cite\Cite->guardedReferences()
#11 /../w/extensions/Cite/src/Hooks/CiteParserTagHooks.php(72): Cite\Cite->references()
#12 /../w/includes/parser/Parser.php(3923): Cite\Hooks\CiteParserTagHooks::references()
#13 /../w/includes/parser/PPFrame_Hash.php(340): Parser->extensionSubstitution()
#14 /../w/includes/parser/Parser.php(2888): PPFrame_Hash->expand()
#15 /../w/includes/parser/Parser.php(1557): Parser->replaceVariables()
#16 /../w/includes/parser/Parser.php(652): Parser->internalParse()
#17 /../w/includes/content/WikitextContent.php(374): Parser->parse()
#18 /../w/includes/content/AbstractContent.php(590): WikitextContent->fillParserOutput()
#19 /../w/includes/Revision/RenderedRevision.php(263): AbstractContent->getParserOutput()
#20 /../w/includes/Revision/RenderedRevision.php(235): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached()
#21 /../w/includes/Revision/RevisionRenderer.php(215): MediaWiki\Revision\RenderedRevision->getSlotParserOutput()
#22 /../w/includes/Revision/RevisionRenderer.php(152): MediaWiki\Revision\RevisionRenderer->combineSlotOutput()
#23 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}()
#24 /../w/includes/Revision/RenderedRevision.php(197): call_user_func()
#25 /../w/includes/Storage/DerivedPageDataUpdater.php(1315): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#26 [internal function]: MediaWiki\Storage\DerivedPageDataUpdater->getCanonicalParserOutput()
#27 /../w/includes/edit/PreparedEdit.php(104): call_user_func()
#28 /../w/includes/edit/PreparedEdit.php(119): MediaWiki\Edit\PreparedEdit->getOutput()
#29 /../w/includes/Storage/DerivedPageDataUpdater.php(1293): MediaWiki\Edit\PreparedEdit->__get()
#30 /../w/includes/page/WikiPage.php(2117): MediaWiki\Storage\DerivedPageDataUpdater->getPreparedEdit()
#31 /../w/extensions/SpamBlacklist/includes/SpamBlacklistHooks.php(34): WikiPage->prepareContentForEdit()
#32 /../w/includes/HookContainer/HookContainer.php(329): SpamBlacklistHooks::filterMergedContent()
#33 /../w/includes/HookContainer/HookContainer.php(132): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#34 /../w/includes/HookContainer/HookRunner.php(1529): MediaWiki\HookContainer\HookContainer->run()
#35 /../w/includes/EditPage.php(1906): MediaWiki\HookContainer\HookRunner->onEditFilterMergedContent()
#36 /../w/includes/EditPage.php(2365): EditPage->runPostMergeFilters()
#37 /../w/includes/EditPage.php(1726): EditPage->internalAttemptSave()
#38 /../w/includes/api/ApiEditPage.php(433): EditPage->attemptSave()
#39 /../w/includes/api/ApiMain.php(1593): ApiEditPage->execute()
#40 /../w/includes/api/ApiMain.php(529): ApiMain->executeAction()
#41 /../w/includes/api/ApiMain.php(500): ApiMain->executeActionWithErrorHandling()
#42 /../w/api.php(90): ApiMain->execute()
#43 /../w/api.php(45): wfApiMain()
#44 {main}
```
Probably related to https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/issues/88

**Comment by octfx** [comment]
Are you certain that you are using tag 3.4.1? 

Looking at the error source `/EmbedVideo/classes/media/AudioTransformOutput.php(102)`; This path hasn't been used since 94968d5b906a5acc508c8dcdfabcf3bf88f214a0.

Can you double check? AudioTransformOutput should be loaded from `includes/Media/TransformOutput`

**Comment by kghbln** [comment]
I must have taken this from the pre-upgrade error log. Senior moments. Indeed, this issue is no longer appearing in the wiki. Please excuse the noise.
