### ISSUE TITLE
MW internal error when using a broken redirect as poster

### ISSUE THREAD

**Issue by Fyren** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#93]
**Describe the bug**
A file link with a poster where the poster is a broken redirect throws an internal MW error.  For example, `[[File:video.webm|poster=brokenredirect.jpg]]`.  If the video doesn't exist or the poster doesn't exist or is just a deleted file (instead of a broken redirect), the problem doesn't occur.  Trace at the bottom.

Depending on whether it's actually on the page or in a preview, something like `Internal error` and `[someid] 2024-04-27 11:56:32: Fatal exception of type "Error"'` or
```
An error occurred while attempting to preview your changes.
[someid] Caught exception of type Error
```

**To Reproduce**
1. Upload a video and an image, say `video.webm` and `poster.jpg`
2. Move `poster.jpg` to `poster2.jpg`
3. Delete `poster2.jpg`, leaving behind `poster.jpg` as broken redirect
4. Using `[[File:video.webm|poster=poster.jpg]]` will cause an error.

**Expected behavior**
Whatever normally happens when the poster is a not actually an image or is missing.

**Technical information:**
Tested on dustloop.com (which uses MW 1.39.6 and EV 3.1.0) and on my local test install (using MW 1.39.6 to match, and EV from git).

```
Error: Call to a member function transform() on bool

Backtrace:

from mwpath\extensions\EmbedVideo\includes\Media\VideoHandler.php(76)
#0 mwpath\includes\filerepo\file\File.php(1202): MediaWiki\Extension\EmbedVideo\Media\VideoHandler->normaliseParams(LocalFile, array)
#1 mwpath\includes\Linker.php(447): File->transform(array)
#2 mwpath\includes\parser\Parser.php(5549): Linker::makeImageLink(Parser, Title, LocalFile, array, array, boolean, boolean, integer)
#3 mwpath\includes\parser\Parser.php(2712): Parser->makeImage(Title, array, LinkHolderArray)
#4 mwpath\includes\parser\Parser.php(2456): Parser->handleInternalLinks2(string)
#5 mwpath\includes\parser\Parser.php(1638): Parser->handleInternalLinks(string)
#6 mwpath\includes\parser\Parser.php(723): Parser->internalParse(string)
#7 mwpath\includes\content\WikitextContentHandler.php(301): Parser->parse(string, Title, ParserOptions, boolean, boolean, NULL)
#8 mwpath\includes\content\ContentHandler.php(1720): WikitextContentHandler->fillParserOutput(WikitextContent, MediaWiki\Content\Renderer\ContentParseParams, ParserOutput)
#9 mwpath\includes\content\Renderer\ContentRenderer.php(47): ContentHandler->getParserOutput(WikitextContent, MediaWiki\Content\Renderer\ContentParseParams)
#10 mwpath\includes\EditPage.php(4535): MediaWiki\Content\Renderer\ContentRenderer->getParserOutput(WikitextContent, Title, NULL, ParserOptions)
#11 mwpath\includes\EditPage.php(4438): EditPage->doPreviewParse(WikitextContent)
#12 mwpath\includes\EditPage.php(3144): EditPage->getPreviewText()
#13 mwpath\includes\EditPage.php(779): EditPage->showEditForm()
#14 mwpath\includes\actions\EditAction.php(73): EditPage->edit()
#15 mwpath\includes\actions\SubmitAction.php(38): EditAction->show()
#16 mwpath\includes\MediaWiki.php(542): SubmitAction->show()
#17 mwpath\includes\MediaWiki.php(322): MediaWiki->performAction(Article, Title)
#18 mwpath\includes\MediaWiki.php(904): MediaWiki->performRequest()
#19 mwpath\includes\MediaWiki.php(562): MediaWiki->main()
#20 mwpath\index.php(50): MediaWiki->run()
#21 mwpath\index.php(46): wfIndexMain()
#22 {main}
```

**Comment by octfx** [comment]
Fixed in develop
